# Generated by Django 6.1 on 2026-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(max_length=50, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
