# Generated by Django 6.1 on 2026-08-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='baggage.baggage')),
            ],
        ),
    ]
