# Generated by Django 6.1 on 2026-08-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0002_baggagelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='baggage.baggage')),
            ],
        ),
    ]
